### PR TITLE
Setuptools

### PR DESCRIPTION
**Pull request by phaustin**
I wanted to figure out setuptools and use eigency, so I made a few changes to move the setup.py files  over from distutils

still rough, but the following works for me on osx:

1) cd eigency; pip install .
2) cd tests; pip install .
3) cd ~; python -m eigency_tests.run_tests -vvv
shows all tests passing

cd eigency; pip wheel .
cd tests; pip wheel .

also seems to build working wheels

thanks for eigency -- Phil

### CODE REVIEW

**Comment by wouterboomsma** [comment]
Hi Phil, Thanks for your contribution. I'm a little uncertain on how to proceed with this. You have made such a substantial reorganization of the code that I find it difficult to maintain a good overview of what has changed - and why. 
Could you perhaps briefly motivate:
 1. What is the advantage of switching to setuptools? (i.e., what can we do now that we couldn't do before)
 2. Is the file-restructuring a direct consequence of the switch to setuptools, or for some other reason?

**Comment by phaustin** [comment]
On 2016-11-02 14:40, Wouter Boomsma wrote:
> Hi Phil, Thanks for your contribution. I'm a little uncertain on how to
> proceed with this. You have made such a substantial reorganization of
> the code that I find it difficult to maintain a good overview of what
> has changed - and why.
> Could you perhaps briefly motivate:
> 
>  1. What is the advantage of switching to setuptools? (i.e., what can we
>     do now that we couldn't do before)
>  2. Is the file-restructuring a direct consequence of the switch to
>     setuptools, or for some other reason?
> 

Hi Wouter -- there's a lot of churn in the various commits, but it's all
related to where to put eigen -- I wasn't able to get a clean uninstall
when I had eigen_3.2.8 located above the eigency/eigency folder, so I
moved it around a couple of times testing things.  Let me confirm that
and then I can submit a fresh pull request if you're interested.

The benefits from my perspective are:

1) clean uninstall all files
2) wheels
3) easier to get setuptools installs working on conda-forge

**Comment by wouterboomsma** [comment]
Hi again, 

I certainly appreciate these efforts. I'm not so familiar with setuptools, so I just need to get used to the idea :) I'll play around with the new setup and see if it works well in my usual setting, and if everything works fine, I'll merge it in - at least if you are happy with the current version.

**Comment by phaustin** [comment]
sounds good -- but why don't you let me submit another request with a
clean history, should be able to get to it this weekend -- best, PHil

**Comment by wouterboomsma** [comment]
Ok. That would be great. Thanks.

**Comment by wouterboomsma** [comment]
Superceded by #12

**Pull request closed without merging**
