### PR TITLE
Fix missing Eigen source code in source distribution

### LINKED ISSUE #13: Release tarball 1.74 does not include eigen source code
The archive [eigency-1.74.tar.gz](https://pypi.python.org/packages/9a/46/db59a9c09b3b4f684917edb58f24daef49463b25811989156984b8147279/eigency-1.74.tar.gz#md5=460575838955a06496a5629ee33c0a0d) does not contain the `eigency/eigen_3.2.8` directory, therefore the build fails.

I might have missed something in #12, although running `python setup.py sdist` locally gives the expected result for me.

### PR DESCRIPTION
**Pull request by sebp**
Hopefully fixes #13.

setuptools only considers package_data when installing the package, whereas MANIFEST.in is used
when creating a source distribution (sdist). Problems might also be related to pypa/setuptools#521, which is why I get a different results with older versions of setuptools (25 vs. 33).

### CODE REVIEW

**Comment by wouterboomsma** [comment]
Thanks. Just to be on the safe side, I checked the eigen library contents compared to the old version, and diff reports the differences below. Was it your intention to leave out these files? In my original version, I included everything since I didn't want to make assumptions about how the Eigen library was used. And it seems that we should at least include the COPYING licence files.

```
$ diff --brief -r dist/eigency-1.74.dev8+nge69cc23/eigency/eigen_3.2.8 dist/eigency-1.73/eigen_3.2.8
Only in dist/eigency-1.73/eigen_3.2.8: .hg_archival.txt
Only in dist/eigency-1.73/eigen_3.2.8: .hgeol
Only in dist/eigency-1.73/eigen_3.2.8: .hgignore
Only in dist/eigency-1.73/eigen_3.2.8: .hgtags
Only in dist/eigency-1.73/eigen_3.2.8: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.BSD
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.GPL
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.LGPL
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.MINPACK
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.MPL2
Only in dist/eigency-1.73/eigen_3.2.8: COPYING.README
Only in dist/eigency-1.73/eigen_3.2.8: CTestConfig.cmake
Only in dist/eigency-1.73/eigen_3.2.8: CTestCustom.cmake.in
Only in dist/eigency-1.73/eigen_3.2.8/Eigen: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Cholesky: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/CholmodSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/arch/AltiVec: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/arch: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/arch/Default: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/arch/NEON: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/arch/SSE: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/products: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Core/util: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Eigen2Support: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Eigen2Support/Geometry: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Eigenvalues: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Geometry: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Geometry/arch: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Householder: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/IterativeLinearSolvers: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/Jacobi: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/LU: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/LU/arch: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/MetisSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/OrderingMethods: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/PaStiXSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/PardisoSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/QR: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SPQRSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SVD: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SparseCholesky: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SparseCore: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SparseLU: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SparseQR: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/StlSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/SuperLUSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/UmfPackSupport: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/misc: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8/Eigen/src/plugins: CMakeLists.txt
Only in dist/eigency-1.73/eigen_3.2.8: INSTALL
Only in dist/eigency-1.73/eigen_3.2.8: bench
Only in dist/eigency-1.73/eigen_3.2.8: blas
Only in dist/eigency-1.73/eigen_3.2.8: cmake
Only in dist/eigency-1.73/eigen_3.2.8: debug
Only in dist/eigency-1.73/eigen_3.2.8: demos
Only in dist/eigency-1.73/eigen_3.2.8: doc
Only in dist/eigency-1.73/eigen_3.2.8: eigen3.pc.in
Only in dist/eigency-1.73/eigen_3.2.8: failtest
Only in dist/eigency-1.73/eigen_3.2.8: lapack
Only in dist/eigency-1.73/eigen_3.2.8: scripts
Only in dist/eigency-1.73/eigen_3.2.8: signature_of_eigen3_matrix_library
Only in dist/eigency-1.73/eigen_3.2.8: test
Only in dist/eigency-1.73/eigen_3.2.8: unsupported
```

**Comment by sebp** [comment]
I updated MANIFEST.in to include all files in the eigen_3.2.8 folder in the source distribution. Only the eigen_3.2.8/Eigen directory is installed as package data.

**Comment by wouterboomsma** [comment]
I understand _what_ you did. I just wanted your opinion about whether it was reasonable to exclude all the files you did. Since eigency supports working with a custom Eigen location, I guess it is indeed reasonable to include only the main Eigen dir in our distribution of eigency - as you did. However, I think we should add the `COPYING*` files back in, to ensure that we are not violating the Eigen license (unless you checked that this is not a problem?).

**Comment by sebp** [comment]
The source distribution now contains only the Eigen folder and the COPYING files.

**Comment by wouterboomsma** [comment]
Thanks. Merged and pushed new release to pypi.

**Pull request merged**
