### PR TITLE
Ci travis

### PR DESCRIPTION
**Pull request by Gjacquenot**
This PR adds CI with travis on linux with python 27, 34,35,36. 

It compiles the eigency, creates package and tests it.

Results can be seen here : https://travis-ci.org/Gjacquenot/eigency

To activate travis-ci, @wouterboomsma you need to create an account on https://travis-ci.org with GitHub credentials. Then, you can add a nice badge in the readme to show everything is fine.

Badge can look like this: 

[Build Status](https://travis-ci.org/Gjacquenot/eigency)

https://travis-ci.org/Gjacquenot/eigency.svg?branch=master

### CODE REVIEW

**Comment by Gjacquenot** [comment]
Thanks for merging: Can you activate the CI and a badge in the Readme.md?

**Comment by wouterboomsma** [comment]
Yes, I was just trying to do this, but the travis build fails for some reason:
```
In file included from eigency_tests/eigency_tests.cpp:568:0:
/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/eigency-1.76.dev17+g55160ee-py2.7.egg/eigency/eigency_cpp.h:10:29: fatal error: conversions_api.h: No such file or directory
 #include "conversions_api.h"
                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```
Perhaps this has something to do with the other PRs I merged in. Did you see similar problems when you set it up originally?

**Comment by wouterboomsma** [comment]
Anyway, added the badge now, so that the whole world can see that it is failing. Not sure this is an improvement :)

**Comment by wouterboomsma** [comment]
Problem solved.

**Comment by Gjacquenot** [comment]
It is really weird: CI failed because cython was not run on pyx files on your first CI attempt.

For me: it succeded: https://travis-ci.org/Gjacquenot/eigency/jobs/340701807#L454

The important is that it is working now!

**Comment by wouterboomsma** [comment]
Yes. This was due to PR #21. I have now rolled this back until we understand how to make it work properly.

**Pull request merged**
